### ISSUE TITLE
怎么没看到接口相关的代码

### ISSUE THREAD

**Issue by WHDevLab** [iizvv/signature#1]
这是全部的代码吗

**Comment by iizvv** [comment]
使用springboot开发。我不太明白接口相关是什么意思

iizvv
________________________________

**Comment by WHDevLab** [comment]
https://api.appstoreconnect.apple.com/v1/apps  类似这个api，应该会有相关的请求代码吧_

**Comment by WHDevLab** [comment]
找到了，在ITSUtils里
