### ISSUE TITLE
超级签名怎么做到安装包包名都一样的？

### ISSUE THREAD

**Issue by WHDevLab** [iizvv/signature#2]
正常一个bundle id 只能存在于一个开发者账户中，蒲公英有很多开发者账户，他是怎么做到包名一致的

**Comment by iizvv** [comment]
创建证书不需要管你的id。可以使用通配符的方式。这些在我的代码中都有体现。

iizvv
________________________________

**Comment by WHDevLab** [comment]
但是mobileprovision中是需要设置证书和bundle id的，而且重签名的时候也需要证书和mobileprovision文件

**Comment by iizvv** [comment]
这些用的都是通配文件。并没有使用固定id

iizvv
________________________________

**Comment by WHDevLab** [comment]
那其实不同的证书签出来的bundle id也是不一样的，如果功能有推送也需要指定固定的bundle ID
吧

**Comment by WHDevLab** [comment]
通配符可以存在不同的开发者账户？

**Comment by iizvv** [comment]
因为我没有测试推送方面的问题。但是通配符是任意账号都可以有的

iizvv
________________________________

**Comment by WHDevLab** [comment]
那如果不用通配符呢，用具体的bundle id，就一定实现不了超级签名吗？

**Comment by iizvv** [comment]
也不是。你可以在重签名的时候直接修改id

iizvv
________________________________

**Comment by WHDevLab** [comment]
但是蒲公英确实是没有修改包名的，都是一个

**Comment by WHDevLab** [comment]
还是不是通配符，就是固定的一个包名

**Comment by iizvv** [comment]
不明白你的意思

iizvv
________________________________

**Comment by WHDevLab** [comment]
就是说不管任何时间，任何人，只要下载蒲公英超级签名签过的应用，bundle id都是一样的，比如 com.wexin.qq

**Comment by iizvv** [comment]
通配符不会修改id

iizvv
________________________________
